### PR TITLE
前端开发-应届生-马秀丽

### PR DESCRIPTION
**Pull request by maxxiaobao**
The task is completed on request and written on the gh-pages branch,looking forward to your reply,thank you!

### CODE REVIEW

**Comment by flyingant** [comment]
Hi @maxxiaobao, 
I'm Mayi. I just reviewed your code and it looks good to me.
For javascript part I would like you to meet the challenge that could you try to use the javascript templating engine instead of combining the html snippet when you render the data to table.(e.g. [handlebars js](https://handlebarsjs.com) or something else you like)

MaYi

**Comment by maxxiaobao** [comment]
@flyingant Because the use of jquery more so choose it,I  will be based on your recommendations to learn and modify the code,thank you very much for taking the time to read my code and make suggestions for me.

**Comment by maxxiaobao** [comment]
Using the handlebars template engine, in the data rendering time is indeed a lot easier,in which I learned a lot.The code has been submitted. Demo address by handlebars <a href="http://maxxiaobao.github.io/test-frontend/index1.html">http://maxxiaobao.github.io/test-frontend/index1.html</a>,At last,hope to be able to join the wiredcraft family !

**Comment by makara** [comment]
Thanks. That should be enough for us to take a decision. Closing.

**Pull request closed without merging**
