### PR TITLE
Implementation of responsive mansory layout

### PR DESCRIPTION
**Pull request by XiayidanAlimu**

### CODE REVIEW

**Comment by flyingant** [comment]
@XiayidanAlimu Would like to explain how you implement the lazy loading feature here?

**Comment by XiayidanAlimu** [comment]
> 

Sorry, I didn't apply feature lazy-loading ..

**Comment by flyingant** [comment]
Would you like to try it and add this feature or share the idea about how you gonna make it?

**Comment by XiayidanAlimu** [comment]
> Would you like to try it and add this feature or share the idea about how you gonna make it?

Hello, effectively, I have attempted to implement lazy-loading image with Intersection Observer API, but I have encountered some issues, because I calculate the number of columns of images at the first stage in order to realize responsive design ... so I didn't submit code about image lazy-loading. The steps that I have tried are as below:
1. in html markup for `img` tag, use `data-src` attribute instead of `src` attribute to put the path of the image
2. In the CSS, I give each image a `min-height` value, `100px`. This gives each image placeholder (the `img` element without the `src` attribute) a vertical dimension
3. In the JavaScript file, I have created a config object and registered it with an `IntersectionObserver` instance
4. I iterate over all of the images and add them to this `InterationObserver` instance

**Comment by flyingant** [comment]
Cool. 
I think those are enough for us to make the decision for the next step.

Thanks.

**Pull request closed without merging**
