### PR TITLE
my test code and previous-works

### PR DESCRIPTION
**Pull request by phoenix-dream**
# ux-response-demo
**a test about responsive page**

1. compatible with standard browsers.
2. just demonstration, not needed for now to compatible with lower version browsers.
3. responsive page layout is also for demonstration, so no need to consider too many UX/UI design issues.

### CODE REVIEW

**Comment by flyingant** [comment]
Hi @phoenix-dream , This is MaYi from the WCL and reviewing your code.

I noticed that you had the code like 
```
 txt += '<tr data-region="' + (current.type) + '" data-search="' + (current.search) + '" data-level="' + (current.level) + '" data-download="' + (current.download) + '" class="data-tree-level-' + (current.level) + '">';
        txt += '<th>';
        txt += '<dl class="data-tree">';
        txt += '<dt class="item-index"><i class="badge">' + (current.badge) + '</i></dt>';
        txt += '<dd class="item-main">';
```

Do you think you can try to implement it by using a template engine library (like underscores js or handlebars js) or React framework to make it looks more elegant or do you have any special consideration?

**Comment by phoenix-dream** [comment]
> Hi @phoenix-dream , This is MaYi from the WCL and reviewing your code.
> 
> I noticed that you had the code like
> 
> ```
>  txt += '<tr data-region="' + (current.type) + '" data-search="' + (current.search) + '" data-level="' + (current.level) + '" data-download="' + (current.download) + '" class="data-tree-level-' + (current.level) + '">';
>         txt += '<th>';
>         txt += '<dl class="data-tree">';
>         txt += '<dt class="item-index"><i class="badge">' + (current.badge) + '</i></dt>';
>         txt += '<dd class="item-main">';
> ```
> 
> Do you think you can try to implement it by using a template engine library (like underscores js or handlebars js) or React framework to make it looks more elegant or do you have any special consideration?

Hi @flyingant
without special consideration.

to demonstrate demo, I try not to rely on external libraries first.
of course, the syntax of React JSX or (ES6 > ``) is more concise.

a similar situation includes CSS.

this is a code style and composite demonstration.

**Comment by flyingant** [comment]
@phoenix-dream Maybe you can try to implement it with SCSS and React? This is a challenge for you

**Comment by phoenix-dream** [comment]
Hi @flyingant, 
a few years ago, when working with others, we often used **Bootstrap + LESS/SCSS**.
I just started to learn React.js, which is really a challenge for React.js.

**Comment by makara** [comment]
Hi @phoenix-dream, not sure I get what you saying. Are you taking the challenge or are you dropping it?

**Comment by makara** [comment]
Closing. Thanks anyway.

**Pull request closed without merging**
