### PR TITLE
front-end-Xiaoyun

### PR DESCRIPTION
**Pull request by xiaaoo-zz**

### CODE REVIEW

**Comment by flyingant** [comment]
Hi @littlebobby, this is MaYi from WCL and I'm reviewing your code. 
I noticed that you are using redux to save/update search criteria but didn't touch any table data. it's confusing. I think we could get a better solution to it.

How do you think if we could:

1. Save all table data into Reducer
2. Use Actions to filter the table data
3. The search criteria should be the params of the Action functions

Could you follow it or if you had a better idea to it?

**Comment by xiaaoo-zz** [comment]
Yes @flyingant. It's indeed a better solution! Here I have updated my code, storing & updating data in the reducer.

 But I am concerned about the its efficiency compared to the previous version, as it now takes two  **for loops**(1. to filter() the data in reducer 2. to rerender data in the Table class by using map()). Anyway, my previous version is certainly a bit messy! Thanks for the correction! 👍

**Comment by flyingant** [comment]
@littlebobby 
You could take it as the kind of one-way data flow.

View -> Actions -> Reducer -> Store -> View

Or you could  just set up your original state like below
```
.....
{
  tableData: []
  filterTableData: []
}
...
```
might be more clear

**Comment by xiaaoo-zz** [comment]
@flyingant. 
It seems creating a separate variable in the redux store, `tableData`, is a bit redundant. Since redux states are meant to deal with system wide / application state and `tableData` will be a **static** variable that won't be mutated or used for rendering state anywhere in our application, I think it's better to keep just one variable in our case (for handling table change).

Here are part of the articles I found, may be helpful. Thanks for your kind suggestion MaYi as always 👍

[for application state - reddit](https://www.reddit.com/r/reactjs/comments/6e0pes/best_practices_structuring_my_redux_store/)

[only stateful data - stackoverflow](https://stackoverflow.com/questions/35875593/should-i-store-never-changing-bootstrapped-data-in-the-store)

**Pull request closed without merging**
