### PR TITLE
Pull Request - Building the app for testing

### PR DESCRIPTION
**Pull request by iEricKoh**
Hi @makara,

I've been so busy for the past month, and so sorry took so long to send you this PR.

Please checkout the [online demo](http://52.197.230.20/) and review the PR.
To learn more how to start, please visit the [README](https://github.com/iEricKoh/test-frontend/blob/master/README.md) on my repo.

### CODE REVIEW

**Comment by EcutDavid** [comment]
Checked your code, looks nice and clean, good work.
Just one tiny problem and would be nice if you can make a quick fix.

The search button is broken, although "ENTER" key works well. 
ovhd9hzocv

**Comment by iEricKoh** [comment]
Hi David,

Thanks for the quick reply.
Actually, the search icon is just a placeholder, not a button.

Shoud I add a button next to input box?

Cheers,
Eric

**Comment by EcutDavid** [comment]
Hmm, it's based on your choice, the target of this test is to give us a chance to check your coding skills and how you manage the project, etc..., so the features it's not a big deal.

By the way, our tech leader is traveling, and will back later this week, you will hear from him soon, LOL.

**Comment by iEricKoh** [comment]
@EcutDavid Yes, but I think the icon still need to improve. I would like to make the icon to disappear when the input has value. I'll fix that later.

Great, hope to hear from him soon.

**Pull request closed without merging**
