### PR TITLE
test PR

### PR DESCRIPTION
**Pull request by fareco**
finish test.

### CODE REVIEW

**Comment by makara** [comment]
Hi @fareco thanks. Could you also update the readme with some instructions of how to start the project etc. Also an online demo would be great.

**Comment by flyingant** [comment]
Hi @fareco, I'm MaYi and  I reviwed your code. 

You are doing well and I would like to challenge you to know more about your skill.
I noticed that you had been use the `grunt`,`scss`, `webpack` etc. Would you please to try something belows:

1. Use `webpack` or `grunt` to pack and build your project
2. Use `scss` with react
3. Use `redux` or other tools to manage your table data.(refactor the `search` logic)
4. Build an online demo

Thanks!

**Comment by makara** [comment]
Hey @fareco please consider the challenge a plus and you can reject; we could already have a conclusion.

**Comment by fareco** [comment]
Hi @makara  @flyingant.

I will challenge the test.

**Comment by fareco** [comment]
Hi @makara @flyingant.
 I  used  `webpack` and `scss` to refactor the test. You can see the [online demo](https://fareco.github.io/test-frontend/).

**Comment by makara** [comment]
Thanks. It should be enough for us to take a decision. Closing.

**Pull request closed without merging**
