### PR TITLE
Jason Wang

### PR DESCRIPTION
**Pull request by xiaojie45**
Hi, i have completed the task, this is the [online demo](https://codepen.io/wxiaojie45/full/KmRZLK/)
test_frontend
this is the test 
test_frontend_test
94qbvr shxz y1 fb5 8 7k

### CODE REVIEW

**Comment by z4rd** [comment]
Hi, Jason.
Thanks for sending us your update,
we will get back to you soon.

**Comment by flyingant** [comment]
Hi @xiaojie45,
I'm Mayi and I'm the frontend developer on Wiredcraft. 
I checked your commits and you doing well on your test and I would like to challenge you to use react to rebuild the page. Because currently we use the reactjs as our primary choice on projects. 

PS: you don't have to build a real app with everything inclued but try to add something new or something you believe it's useful.

Thanks

**Comment by xiaojie45** [comment]
@flyingant  ok,  i haven't used react before, so i need some time to learn it first
for your PS, do you mean besides those functionalities you have required  in the task, i should add something new to the page?

**Comment by flyingant** [comment]
@xiaojie45 
Nono, just stick on the current requirements in the task.

I noticed that you used the vuex from your previous work and done well. But in my humble opinion for the current task there's not too much necessary to use a state management tool. It's just a little bit over-designed. You could try to focus on the code itself. As example, you could try to separate the css from the .vue file or try the css preprocessing tool like [**scss**](https://sass-lang.com/) and bundle them(You don't have to do it right now but you could take it as an advice!). 

We wish to know more about how deep you know about those techs.

Best

**Comment by xiaojie45** [comment]
@flyingant  ok, i will use scss and react to rebuild this page

**Comment by xiaojie45** [comment]
@flyingant  hi, i have rebuilt the page by using react and sass ,this is [online demo](http://s.codepen.io/wxiaojie45/debug/zwMjxE/xJMjOWqodVQr)

**Comment by flyingant** [comment]
@xiaojie45 the line for your online demo is expired. lol

**Comment by xiaojie45** [comment]
@flyingant  sorry,  you can check this link to have a preview [demo](http://codepen.io/wxiaojie45/pen/zwMjxE/)

**Comment by makara** [comment]
Thanks @xiaojie45. That should be enough for us to a decision. Will back to you soon. Closing.

**Pull request closed without merging**
