### PR TITLE
Test-frontend

### PR DESCRIPTION
**Pull request by uetuluk**
My attempt at creating the website shown at the mockup

### CODE REVIEW

**Comment by flyingant** [comment]
Hi @uetuluk, This is MaYi from Wiredcraft.
Just review the code and feels you are doing great.

Then I would like to challenge you something.

1. Could you try to use webpack or parcel on your project? (Those module bundler tools could help you to bundle your application) 
2. Try to import the SCSS to your project.

**Comment by uetuluk** [comment]
Hello @flyingant,
Thank you for the feedback!
I will implement those functions on Wednesday and update the code and the demo accordingly.

**Comment by johncalvinroberts** [comment]
Hi @uetuluk nice work so far!

Also a small challenge from me:

Can you try updating the filter/search bar to look more like the mockup? Notice the border radius and background color. May require some css magic.

Screen Shot 2019-04-01 at 18 24 31

**Comment by uetuluk** [comment]
@flyingant,
Thank you for the packaging challenge, I can see the difference in load time.
@johncalvinroberts 
Thank you for the CSS challenge. I have changed the border-radius to fit the mockup, but I am not sure what you mean by the background color, as far as I can tell it is the same.

**Pull request closed without merging**
