### PR TITLE
Drakexiang front-end test

### PR DESCRIPTION
**Pull request by DrakeXiang**
Finally finished :)
Looking forward to your reply~

### CODE REVIEW

**Comment by flyingant** [comment]
@DrakeXiang I cannot run the project from local successfully and the `npm run build` seems not working as expected. Would you like to check the webpack config?

**Comment by DrakeXiang** [comment]
> @DrakeXiang I cannot run the project from local successfully and the `npm run build` seems not working as expected. Would you like to check the webpack config?

Thanks for the feedback, I tested `npm run build` with fresh `npm install`, everything works fine, not sure what went wrong on your machine. Although I think I missed the json data serve procedure in the doc.. Basically I used `http-server` package as a simple server at `http://127.0.0.1:8080/data.json` to serve the `data.json` file from local, so maybe this is why you failed to run? 

I'll try to make it right and push another commit.

**Comment by flyingant** [comment]
OK, Thank you. Just let us know when you re ready

**Comment by DrakeXiang** [comment]
@flyingant I've added some doc, please run `npm install` and  try again, let me know if you still have issues running or building the project

**Pull request closed without merging**
