### PR TITLE
Elaine branch

### PR DESCRIPTION
**Pull request by 2857**
Still got some problems about 
1 . the table nested -- state --- district ---- township 
2.  the ui responsive test and function test 
3. only has search function without searching via filter

i will fix it and commit later

### CODE REVIEW

**Comment by makara** [comment]
Thanks @aliencyl7 . You can keep hacking it but this should be enough for us to evaluate. We'll get back to you soon. Meanwhile can you describe a few things:
- What do you think the data structure should look like? And why?
- Do you see anything wrong or weird on the mock?
- How do you (in your code) decide which item is expended? And how is that related to the data structure?

**Comment by 2857** [comment]
Fixed the filter problem and nested table problem
Commited to the elaine_branch

ezgif com-video-to-gif 1

**Comment by makara** [comment]
Thanks @aliencyl7 ; looks good. Do you have any comments to my last questions?

**Comment by makara** [comment]
Thanks. Closing.

**Pull request closed without merging**
